spring:
  application:
    name: yw-live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml
    hikari:
      pool-name: yw-live-user-pool
      minimum-idle: 2
      maximum-pool-size: 20
      connection-timeout: 3000
      max-lifetime: 60000

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://192.168.211.132:8848/nacos?namespace=b7e7f031-ad7b-4a1f-98a7-a315bd105b26&&username=nacos&&password=www.yyj.com
  protocol:
    name: dubbo
    port: 9091