server:
  port: 8080
spring:
  application:
    name: yw-live-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      username: nacos
      password: www.yyj.com
      discovery:
        namespace: b7e7f031-ad7b-4a1f-98a7-a315bd105b26
        server-addr: 192.168.211.132:8848
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://192.168.211.132:8848/nacos?namespace=b7e7f031-ad7b-4a1f-98a7-a315bd105b26&&username=nacos&&password=www.yyj.com